### PR TITLE
Updated Dockerfile to allow building

### PR DESCRIPTION
**Pull request by tidalvirus**
background: I'm totally new to dotnet, and this is also my first Dockerfile.

I wanted to be able to build and deploy this container on a linux server that I use for multiple containers - as well as my home-assistant install (also in a container). A lot of this was trial and error - the main components were taken from the documentation, and I merged some of your previous DockerFile into it in what I hope was the correct area.

Please check, and if useful, feel free to merge it in!

PS. This is also my first pull request ;)

### CODE REVIEW

**Comment by ozczecho** [comment]
Thanks for submitting this. I wont have a chance to look at it for a week or so - but I do appreciate it and will look at adding it once I get back.
Mike

    On Saturday, 14 November 2020, 6:49:08 pm AEDT, tidalvirus <notifications@github.com> wrote:  
 
 
background: I'm totally new to dotnet, and this is also my first Dockerfile.

I wanted to be able to build and deploy this container on a linux server that I use for multiple containers - as well as my home-assistant install (also in a container). A lot of this was trial and error - the main components were taken from the documentation, and I merged some of your previous DockerFile into it in what I hope was the correct area.

Please check, and if useful, feel free to merge it in!

PS. This is also my first pull request ;)

You can view, comment on, or merge this pull request online at:

  https://github.com/ozczecho/vzduch-dotek/pull/3

Commit Summary
   
   - dockerfile that allows building
   - added runtimeidentifier for building
   - updated instructions for building with Docker
   - Removed DockerFile - as a new 'Dockerfile' exists.

File Changes
   
   -  D DockerFile (26) 
   -  A Dockerfile (30) 
   -  M README.md (18) 
   -  M VzduchDotek.Net.csproj (1) 

Patch Links:
   
   - https://github.com/ozczecho/vzduch-dotek/pull/3.patch
   - https://github.com/ozczecho/vzduch-dotek/pull/3.diff

**Comment by ozczecho** [comment]
Merged

**Comment by Grubs** [comment]
Would it be possible to create a file/instructions so I can set this up using docker-ce? I'm running Portainer.io to manage my dockers

**Comment by tidalvirus** [comment]
Hi @Grubs - sorry for the extremely slow response. I also do not know anything about portainer. But docker-ce is basically 'docker' as most of us know. What exactly are you trying to do - is it portainer related, or not? If not portainer related, I might be able to help. But I use docker-compose instead of normal docker cli commands...

**Pull request closed without merging**
